apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-1
  region: us-east-2
  version: "1.33"

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: t3.xlarge
    desiredCapacity: 3
    minSize: 3
    maxSize: 6

addons:
- name: aws-ebs-csi-driver
  wellKnownPolicies:
    ebsCSIController: true

